package com.orionhealth.com_orchestral_portal_webservice_api_7_2_user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-15T15:32:43.449+12:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", name = "com.orchestral.portal.webservice.api_7_2.user.UserManagementService")
@XmlSeeAlso({com.orionhealth.com_orchestral_portal_webservice_api_7_2.ObjectFactory.class})
public interface ComOrchestralPortalWebserviceApi72UserUserManagementService {

    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.ResetPassword")
    @WebMethod
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.ResetPasswordResponse")
    public void resetPassword(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String password
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "findUsers", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.FindUsers")
    @WebMethod
    @ResponseWrapper(localName = "findUsersResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.FindUsersResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUsersResponseDto findUsers(
        @WebParam(name = "searchCriteria", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.FindUsersSearchCriteria searchCriteria
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.UpdateUser")
    @WebMethod
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.UpdateUserResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.User updateUser(
        @WebParam(name = "user", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.User user
    ) throws Exception;

    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.DeleteUser")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "authenticateUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.AuthenticateUser")
    @WebMethod
    @ResponseWrapper(localName = "authenticateUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.AuthenticateUserResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.AuthenticateUserResponseDto authenticateUser(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String password
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "evaluatePasswordStrength", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.EvaluatePasswordStrength")
    @WebMethod
    @ResponseWrapper(localName = "evaluatePasswordStrengthResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.EvaluatePasswordStrengthResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.EvaluatePasswordStrengthResponseDto evaluatePasswordStrength(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String password,
        @WebParam(name = "locale", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.LocaleDto locale
    ) throws Exception;

    @RequestWrapper(localName = "enableUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.EnableUser")
    @WebMethod
    @ResponseWrapper(localName = "enableUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.EnableUserResponse")
    public void enableUser(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId
    ) throws Exception;

    @RequestWrapper(localName = "disableUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.DisableUser")
    @WebMethod
    @ResponseWrapper(localName = "disableUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.DisableUserResponse")
    public void disableUser(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.ChangePassword")
    @WebMethod
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.ChangePasswordResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.ChangePasswordResponseDto changePassword(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String password
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUsers")
    @WebMethod
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUsersResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUsersResponseDto getUsers(
        @WebParam(name = "searchCriteria", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.SearchCriteria searchCriteria
    ) throws Exception;

    @RequestWrapper(localName = "renameUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.RenameUser")
    @WebMethod
    @ResponseWrapper(localName = "renameUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.RenameUserResponse")
    public void renameUser(
        @WebParam(name = "oldUserId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String oldUserId,
        @WebParam(name = "newUserId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String newUserId
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "isPasswordChangeForced", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.IsPasswordChangeForced")
    @WebMethod
    @ResponseWrapper(localName = "isPasswordChangeForcedResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.IsPasswordChangeForcedResponse")
    public boolean isPasswordChangeForced(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.CreateUser")
    @WebMethod
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.CreateUserResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.User createUser(
        @WebParam(name = "user", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.User user
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUserResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.User getUser(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "getUserByExternalIdentifier", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUserByExternalIdentifier")
    @WebMethod
    @ResponseWrapper(localName = "getUserByExternalIdentifierResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUserByExternalIdentifierResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.User getUserByExternalIdentifier(
        @WebParam(name = "externalIdentifier", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.ExternalIdentifierDto externalIdentifier
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "getUserByIdentity", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUserByIdentity")
    @WebMethod
    @ResponseWrapper(localName = "getUserByIdentityResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUserByIdentityResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.User getUserByIdentity(
        @WebParam(name = "userId", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String userId
    ) throws Exception;

    @WebResult(name = "return", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
    @RequestWrapper(localName = "getMembersOfGroup", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetMembersOfGroup")
    @WebMethod
    @ResponseWrapper(localName = "getMembersOfGroupResponse", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", className = "com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetMembersOfGroupResponse")
    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.MembersOfGroupDto getMembersOfGroup(
        @WebParam(name = "groupName", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
        java.lang.String groupName
    ) throws Exception;
}
