
package com.orionhealth.com_orchestral_portal_webservice_api_7_2_user;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-15T15:32:43.379+12:00
 * Generated source version: 3.0.1
 * 
 */
public final class ComOrchestralPortalWebserviceApi72UserUserManagementService_ComOrchestralPortalWebserviceApi72UserUserManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/", "UserManagementService");

    private ComOrchestralPortalWebserviceApi72UserUserManagementService_ComOrchestralPortalWebserviceApi72UserUserManagementServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserManagementService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserManagementService ss = new UserManagementService(wsdlURL, SERVICE_NAME);
        ComOrchestralPortalWebserviceApi72UserUserManagementService port = ss.getComOrchestralPortalWebserviceApi72UserUserManagementServicePort();  
        
        {
        System.out.println("Invoking resetPassword...");
        java.lang.String _resetPassword_userId = "";
        java.lang.String _resetPassword_password = "";
        try {
            port.resetPassword(_resetPassword_userId, _resetPassword_password);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findUsers...");
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.FindUsersSearchCriteria _findUsers_searchCriteria = null;
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUsersResponseDto _findUsers__return = port.findUsers(_findUsers_searchCriteria);
            System.out.println("findUsers.result=" + _findUsers__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateUser...");
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _updateUser_user = null;
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _updateUser__return = port.updateUser(_updateUser_user);
            System.out.println("updateUser.result=" + _updateUser__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteUser...");
        java.lang.String _deleteUser_userId = "";
        try {
            port.deleteUser(_deleteUser_userId);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking authenticateUser...");
        java.lang.String _authenticateUser_userId = "";
        java.lang.String _authenticateUser_password = "";
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.AuthenticateUserResponseDto _authenticateUser__return = port.authenticateUser(_authenticateUser_userId, _authenticateUser_password);
            System.out.println("authenticateUser.result=" + _authenticateUser__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking evaluatePasswordStrength...");
        java.lang.String _evaluatePasswordStrength_userId = "";
        java.lang.String _evaluatePasswordStrength_password = "";
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.LocaleDto _evaluatePasswordStrength_locale = null;
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.EvaluatePasswordStrengthResponseDto _evaluatePasswordStrength__return = port.evaluatePasswordStrength(_evaluatePasswordStrength_userId, _evaluatePasswordStrength_password, _evaluatePasswordStrength_locale);
            System.out.println("evaluatePasswordStrength.result=" + _evaluatePasswordStrength__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enableUser...");
        java.lang.String _enableUser_userId = "";
        try {
            port.enableUser(_enableUser_userId);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking disableUser...");
        java.lang.String _disableUser_userId = "";
        try {
            port.disableUser(_disableUser_userId);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking changePassword...");
        java.lang.String _changePassword_userId = "";
        java.lang.String _changePassword_password = "";
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.ChangePasswordResponseDto _changePassword__return = port.changePassword(_changePassword_userId, _changePassword_password);
            System.out.println("changePassword.result=" + _changePassword__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUsers...");
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.SearchCriteria _getUsers_searchCriteria = null;
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.GetUsersResponseDto _getUsers__return = port.getUsers(_getUsers_searchCriteria);
            System.out.println("getUsers.result=" + _getUsers__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking renameUser...");
        java.lang.String _renameUser_oldUserId = "";
        java.lang.String _renameUser_newUserId = "";
        try {
            port.renameUser(_renameUser_oldUserId, _renameUser_newUserId);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking isPasswordChangeForced...");
        java.lang.String _isPasswordChangeForced_userId = "";
        try {
            boolean _isPasswordChangeForced__return = port.isPasswordChangeForced(_isPasswordChangeForced_userId);
            System.out.println("isPasswordChangeForced.result=" + _isPasswordChangeForced__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createUser...");
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _createUser_user = null;
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _createUser__return = port.createUser(_createUser_user);
            System.out.println("createUser.result=" + _createUser__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUser...");
        java.lang.String _getUser_userId = "";
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _getUser__return = port.getUser(_getUser_userId);
            System.out.println("getUser.result=" + _getUser__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserByExternalIdentifier...");
        com.orionhealth.com_orchestral_portal_webservice_api_7_2.ExternalIdentifierDto _getUserByExternalIdentifier_externalIdentifier = null;
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _getUserByExternalIdentifier__return = port.getUserByExternalIdentifier(_getUserByExternalIdentifier_externalIdentifier);
            System.out.println("getUserByExternalIdentifier.result=" + _getUserByExternalIdentifier__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserByIdentity...");
        java.lang.String _getUserByIdentity_userId = "";
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.User _getUserByIdentity__return = port.getUserByIdentity(_getUserByIdentity_userId);
            System.out.println("getUserByIdentity.result=" + _getUserByIdentity__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMembersOfGroup...");
        java.lang.String _getMembersOfGroup_groupName = "";
        try {
            com.orionhealth.com_orchestral_portal_webservice_api_7_2.MembersOfGroupDto _getMembersOfGroup__return = port.getMembersOfGroup(_getMembersOfGroup_groupName);
            System.out.println("getMembersOfGroup.result=" + _getMembersOfGroup__return);

        } catch (Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
