
package com.orionhealth.com_orchestral_portal_webservice_api_7_2_user;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-15T15:32:43.430+12:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "Exception", targetNamespace = "http://www.orionhealth.com/com.orchestral.portal.webservice.api_7_2.user/")
public class Exception extends java.lang.Exception {
    
    private com.orionhealth.com_orchestral_portal_webservice_api_7_2.Exception exception;

    public Exception() {
        super();
    }
    
    public Exception(String message) {
        super(message);
    }
    
    public Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception(String message, com.orionhealth.com_orchestral_portal_webservice_api_7_2.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception(String message, com.orionhealth.com_orchestral_portal_webservice_api_7_2.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.orionhealth.com_orchestral_portal_webservice_api_7_2.Exception getFaultInfo() {
        return this.exception;
    }
}
